sharedservice:
  client: "OpenAI"
  init: 
    base_url: ""
    api_key: ""
  model: ""
  completion_params:
    extra_body:
      chat_template_kwargs:
        enable_thinking: true

semic:
  client: "AzureOpenAI"
  init:
    base_url: ""
    api_key: ""
    api_version: ""
  model: ""
  completion_params:
    extra_body:
      chat_template_kwargs:
        enable_thinking: false
