# which API to use (cfr. .client_config.yaml), amongst
    # - sharedservice
    # - semic
API = "sharedservice"
SERVER_URL = ""

AZURE_OPENAI_API_KEY = ""
AZURE_OPENAI_ENDPOINT = ""

# sharedservice
SHARED_SERVICE_OPENAI_URL = ""
RAG_CHATBOT_API_KEY = ''
LLM_MODEL = ''
EMBEDDING_MODEL = ''
